# Generated by Django 3.1.12 on 2025-04-30 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listings',
            old_name='descriptiom',
            new_name='description',
        ),
    ]
