# Generated by Django 3.1.12 on 2025-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20250430_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
